
name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag distributed.azurecr.io/${{vars.IMAGE_NAME}}:latest

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: distributed.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets. DOCKER_PASSWORD }}

      - name: Push image to Registry
        run: docker push distributed.azurecr.io/${{ vars.IMAGE_NAME }}:latest
